name: Angular 15

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message #- Identifica que es un nuevo item dentro de steps
        run: |
          echo "Hello world!"
      - name :  Get date
        run: ls -l
